# Generated by Django 5.0.4 on 2024-04-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytype',
            old_name='nome',
            new_name='name',
        ),
    ]
