# Generated by Django 5.0.4 on 2024-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address_description_client_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
