# Generated by Django 5.0.4 on 2024-05-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_slug_categorytype_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='stockitem_id',
            new_name='stockitem',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorytype_id',
            new_name='categorytype',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
